name: Kibot build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot_build.yml
        dir: kibot_outputs
        schema: 'kicad/riotee-cap-shield.kicad_sch'
        board: 'kicad/riotee-cap-shield.kicad_pcb'

    - name: Force permissions (kibot messes them up)
      run: sudo chown -R 1001:1001 kibot_outputs

    - name: Upload artifacts to github
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: kibot_outputs

    - name: Upload artifacts to webserver
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: www.riotee.nessie-circuits.de
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: kibot_outputs/
        server-dir: /htdocs/riotee/artifacts/capacitor_shield/latest/
        protocol: ftps
